### ISSUE TITLE
Will this work with the Adesso MSR-100 USB reader?

### ISSUE THREAD

**Issue by nicksellis102** [jarmyo/MSR-100-Magnetic-Stripe-Parser#2]
**Describe the solution you'd like**
I'm specifically looking for a library that will work with an Adesso MSR-100 USB reader and hoping this one will work.

**Describe alternatives you've considered**
I've searched through a few different libraries and this one keeps popping up, I'm hoping that even without a serial port that this will still work. I am waiting on the reader so I have been unable to test. My other option is to code from scratch but I'm needing something quickly.

**Comment by jarmyo** [comment]
I don't have an Adesso MSR-100 USB reader to test.
The main difference, I think, is USB vs Serial Port. In my past experience USB card readers work like keyboards in the same way some barcode readers work, so, each time you swipe, you get a kind of typing with the string.
but if the raw string data is the same, you can reuse the parsing methods, in that case you need to replace the Controller constructor to replace the datarecived event for any that catch keyboard event and pass the recived string.

**Comment by nicksellis102** [comment]
Thank you so much for your fast response! I wasn't expecting one for a couple of days. I am brand new to the card reader world and just trying to build a loyalty/gift card system if you have any recommendations?

**Comment by jarmyo** [comment]
I developed this as part of a Point-of-Sale system (with loyalty card feature for restaurants) the reason Why I use COM port is because most places have old legacy systems with com ports and majority of POS terminals have COM ports.
This parse library works with credit card info standard, if you are going to implement your own cards with your own format this library won't be useful only for the COM connection.
for example, you can print gift cards with QR and have a barcode scanner to read the member info.

Regards.

**Comment by nicksellis102** [comment]
Thanks again and I appreciate the suggestion, thanks for taking the time to respond, and best regards. Best of luck with future projects!
